[profile.ci]
retries = 0
fail-fast = false
slow-timeout = { period = "60s", terminate-after = 10 } # Timeout 10m for `txn_split_batch`.
failure-output = "final"

[profile.ci.junit]
path = "junit.xml"
