[coprocessor]
region-split-keys = 150
batch-split-limit = 100

[raftstore]
region-split-check-diff = "1B"
pd-heartbeat-tick-interval = "2s"
pd-store-heartbeat-tick-interval = "5s"
split-region-check-tick-interval = "1s"
raft-entry-max-size = "256KiB"

[rocksdb]
max-open-files = 10000

[raftdb]
max-open-files = 10000

[storage]
reserve-space = "0MiB"
